# Generated by Django 4.2.2 on 2023-06-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_inventory_stock_inventory_supplier'),
        ('accounts', '0002_delete_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='supplier',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_supplier', to='inventory.supplier'),
        ),
    ]
