# Generated by Django 4.2.2 on 2023-06-30 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_inventory_stock_inventory_supplier'),
        ('accounts', '0003_customuser_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_city', to='inventory.city'),
        ),
    ]
